name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        run: npx cypress run --spec //cypress/e2e/RedbusBooking/EMTFlightSearch.cy.js --headless --browser chrome
